# Generated by Django 2.2.6 on 2020-10-17 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_receita', models.CharField(max_length=200, verbose_name='nome da receita')),
                ('ingredientes', models.TextField()),
                ('modo_preparo', models.TextField(verbose_name='modo de preparo')),
                ('tempo_preparo', models.IntegerField(verbose_name='tempo de preparo')),
                ('rendimento', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('data_receita', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='data da receita')),
            ],
        ),
    ]
